### PR TITLE
Added margins to UI

### PR DESCRIPTION
**Pull request by JamesWrigley**
Hi there,
I made a few small changes to add margins to some buttons at the ends of the file browser header + footer, and also to center the filenames in the context menus. I also added a few more patterns in .gitignore for Emacs.

### CODE REVIEW

**Comment by fabiencastan** [comment]
Hi,
Thanks for the pull request.
I'm currently in holidays, but I will check and merge it in 1 week.

**Comment by JamesWrigley** [comment]
Righto, thanks :)

**Comment by JamesWrigley** [comment]
Update: Another minor change to center the filenames in listview mode.

**Comment by fabiencastan** [comment]
Mostly merged by without using anchors.

We try to avoid using anchors for positionning because it conflicts with Layouts.
It's fine to use "anchors.margins", "anchors.fill", etc. but not for positionning like "anchors.right: parent.right" as we could do the same with RowLayout.

Please notify me if I missed something in your pull request. I have tried to achieve the same result.

**Comment by JamesWrigley** [comment]
Ah I see, will keep that in mind. One minor note though, the filenames in the list view aren't centered vertically.

**Pull request closed without merging**
