### PR TITLE
New dialogs

### LINKED ISSUE #72: Popup window on close
It's not the same popup, if we close the application using the menu ("File>Exit") or using the window cross button.

### PR DESCRIPTION
**Pull request by JamesWrigley**
Hi there :)
I've been working on some new dialogs for a while and I think it's ready to merge now.
Some notes:
- The dialogs created when clicking the titlebar close button or hitting Alt + F4 are not modal, I haven't figured out how to do that yet (they are modal when launched from QML).
- For some reason the path of the initial folder for the FileViewerDialog's will not be displayed when launched from QML, but will when created as a component from `main.py`.
- Changing folder in a FileViewerDialog causes masses of errors, I think because `FolderListModel.get()` returns a `variant` (line 133), which technically may not have a `.toLowerCase()`. Would be nice to suppress these if no solution can be found.

ToDo: 
I'm also a little unsure of the way the code works with `EventFilter()` in `main.py`. Dunno if it's the cleanest way to create the dialogs.

This fixes #72.

### CODE REVIEW

**Comment by fabiencastan** [comment]
I'm interested to merge this PR. But there are 2 problems:
- when opening the application, the Graph widget is hidden
- the "save as" window crashes the application

**Comment by JamesWrigley** [comment]
Hmm, weird. I'm having some trouble getting ButtleOFX going, but will fix this as soon as I can.

**Comment by JamesWrigley** [comment]
I can confirm the graph widget being hidden in the default view, but the Save As dialog works fine here. How does it crash for you?

**Comment by aoblet** [comment]
Merge in progress, some troubles with FileModelFolder are occurring. Do you mind if I update the graphic dialogs to new graphic browser ?

**Comment by aoblet** [comment]
As we have implemented a new browser, I think use it in openGraph and saveGraph is better. It is more homogeneous, and more friendly (we can use browser features).

cropped-buttle

**Comment by JamesWrigley** [comment]
Sure, do whatever you want with it (I'd love to help, but unfortunately ButtleOFX doesn't run on my system).

And nice work on the browser, it looks good :)

**Pull request merged**
